version: '3.8'
services:
  activemq:
    image: rmohr/activemq:latest
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - app_network

  backend-sensores:
    build: .
    ports:
      - "8082:8082"
    environment:
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq:61616
    networks:
      - app_network
    depends_on:
      - activemq

networks:
  app_network:
    driver: bridge
