# ==========================================
# Configuración del servidor y aplicación
# ==========================================
# Define el puerto HTTP en el que se levantará el servidor web para Tomcat.
server.port=8082

# ==========================================
# Configuración de Base de Datos H2 (En Memoria)
# ==========================================
# URL de conexión JDBC para H2. "mem:" indica que la base de datos vivirá en la memoria de la RAM.
# "sensoresdb" es el nombre lógico de nuestra base de datos.
spring.datasource.url=jdbc:h2:mem:sensoresdb

# Nombre de usuario por defecto para H2. No es necesario modificarlo para desarrollo local.
spring.datasource.username=sa

# Contraseña en blanco. Como es una base de datos en memoria y temporal, es seguro y común dejarla sin clave.
spring.datasource.password=

# Clase del driver JDBC oficial, lo cual permite que la aplicación Java se comunique con el motor H2.
spring.datasource.driver-class-name=org.h2.Driver

# ==========================================
# Configuración de la Consola Web de H2
# ==========================================
# Habilita un visor (consola web integrada) para interactuar visualmente con las tablas y ver los datos guardados.
spring.h2.console.enabled=true

# Ruta web personalizada para acceder a la consola. Puedes entrar a: http://localhost:8080/h2-console
spring.h2.console.path=/h2-console

# Permite que la consola de H2 se muestre sin bloqueos si tienes configuraciones de seguridad extras configuradas.
spring.h2.console.settings.web-allow-others=true

# ==========================================
# Configuración de JPA / Hibernate
# ==========================================
# Actualiza automáticamente la estructura de la base de datos (creará la tabla "datos_sensor" cada vez que inicie, ya que la memoria se pierde al apagar).
spring.jpa.hibernate.ddl-auto=update

# Obliga a Spring a imprimir todas las sentencias SQL (INSERT, SELECT...) en la consola inferior para monitorear qué está guardando.
spring.jpa.show-sql=true

# Ajusta explícitamente a Hibernate para que utilice las traducciones lógicas e instrucciones SQL precisas compatibles con el motor de base de datos H2.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Mejora la legibilidad de los logs SQL que salen impresos en la terminal, añadiendo sangrías y saltos de línea ordenados.
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# Configuración del Broker ActiveMQ
# ==========================================
# Conexión al ActiveMQ local en el puerto por defecto de mensajería (61616)
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

# Configura JMS a modo de Publicación/Suscripción explícito (Topics) en lugar del modo por defecto (Colas P2P).
spring.jms.pub-sub-domain=true
