server:
  port: 8761

spring:
  application:
    name: discover-server
  config:
    import: "optional:configserver:http://localhost:8888" # Esto busca el config server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # Esto obliga a no registrarse
    fetch-registry: false       # Esto obliga a no buscar a otros
  server:
    enable-self-preservation: false