server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://discover-server:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/auth/**

        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/catalog/**

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**