server:
  # Puerto estandar de entrada para todas las peticiones (Gateway)
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Ruta hacia el servicio de seguridad (login/register)
            - id: security-service-auth
              uri: lb://security-service
              predicates:
                - Path=/api/auth/**

            # Ruta hacia el CRUD de usuarios
            - id: security-service-users
              uri: lb://security-service
              predicates:
                - Path=/api/users/**

            # Ruta hacia el catalogo de propiedades
            - id: catalog-service
              uri: lb://catalog-service
              predicates:
                - Path=/api/catalog/**

            # Ruta hacia el servicio de reservaciones y pagos PayPal
            - id: booking-service
              uri: lb://booking-service
              predicates:
                - Path=/api/bookings/**

eureka:
  client:
    service-url:
      defaultZone: http://discover-server:8761/eureka/
  instance:
    prefer-ip-address: true
