server:
  port: 8888


spring:
  application:
    name: config-server
  profiles:
    active: native # Indica que lea la carpeta local
  cloud:
    config:
      server:
        native:
          # Ruta donde estaran las configuraciones
          search-locations: classpath:/config-repo, file:./config-repo
