version: '3.8'

services:

  # -------------------------
  # BASES DE DATOS
  # -------------------------

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user_hotel
      POSTGRES_PASSWORD: password_hotel
      POSTGRES_DB: hotel_relational_db
    ports:
      - "5432:5432"
    networks:
      - hotel-network

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017" # Puerto expuesto y requerido para que catalog-service y security-service guarden datos
    networks:
      - hotel-network

  # -------------------------
  # INFRAESTRUCTURA SPRING CLOUD
  # -------------------------

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/config-repo
    environment:
      SPRING_PROFILES_ACTIVE: native
    networks:
      - hotel-network

  discover-server:
    build: ./discover-server # o discovery-server dependiente del directorio
    container_name: discover-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - hotel-network

  # -------------------------
  # MICROSERVICIOS DE NEGOCIO
  # -------------------------

  security-service:
    build: ./security-service
    container_name: security-service
    ports:
      - "8088:8088"
    depends_on:
      - discover-server
      - mongo-db
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discover-server:8761/eureka/
    networks:
      - hotel-network

  catalog-service:
    build: ./catalog-service
    container_name: catalog-service
    ports:
      - "8081:8081"
    depends_on:
      - discover-server
      - mongo-db
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discover-server:8761/eureka/
    networks:
      - hotel-network

  # Servicio integral de Pago y Reservas
  booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - "8082:8082"
    depends_on:
      - discover-server
      # Booking consume PostgreSQL de forma estricta (JPA)
      - postgres-db
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discover-server:8761/eureka/
    networks:
      - hotel-network

  # -------------------------
  # API GATEWAY
  # -------------------------

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discover-server
      - security-service
      - catalog-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discover-server:8761/eureka/
    networks:
      - hotel-network

# -------------------------
# REDES PERSONALIZADAS
# -------------------------
networks:
  hotel-network:
    driver: bridge
