# docker-compose configuracion hibrida

services:

  # -------------------------
  # BASES DE DATOS
  # -------------------------

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user_hotel
      POSTGRES_PASSWORD: password_hotel
      POSTGRES_DB: hotel_relational_db
    ports:
      - "5432:5432"
    networks:
      - hotel-network

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017" # Puerto expuesto y requerido para que catalog-service y security-service guarden datos
    networks:
      - hotel-network

  # -------------------------
  # INFRAESTRUCTURA SPRING CLOUD
  # -------------------------

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/config-repo
    environment:
      SPRING_PROFILES_ACTIVE: native
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - hotel-network

  discover-server:
    build: ./discover-server
    container_name: discover-server
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    networks:
      - hotel-network

  # -------------------------
  # MONITOREO Y TRAZABILIDAD
  # -------------------------
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - hotel-network

  # -------------------------
  # MICROSERVICIOS DE NEGOCIO
  # -------------------------

  security-service:
    build: ./security-service
    container_name: security-service
    ports:
      - "8088:8088"
    depends_on:
      config-server:
        condition: service_healthy
      discover-server:
        condition: service_started
      mongo-db:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discover-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-db:27017/hotel_security_db
    networks:
      - hotel-network

  catalog-service:
    build: ./catalog-service
    deploy:
      replicas: 2
    depends_on:
      config-server:
        condition: service_healthy
      discover-server:
        condition: service_started
      mongo-db:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discover-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-db:27017/hotel_catalog_db
    networks:
      - hotel-network

  # Servicio integral de Pago y Reservas
  booking-service:
    build: ./booking-service
    deploy:
      replicas: 2
    depends_on:
      config-server:
        condition: service_healthy
      discover-server:
        condition: service_started
      # Booking consume PostgreSQL de forma estricta (JPA)
      postgres-db:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discover-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    networks:
      - hotel-network

  # Reseñas de usuarios
  review-service:
    build: ./review-service
    container_name: review-service
    ports:
      - "8083:8083"
    depends_on:
      config-server:
        condition: service_healthy
      discover-server:
        condition: service_started
      postgres-db:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discover-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    networks:
      - hotel-network

  # Notificaciones y reportes
  notification-service:
    build: ./notification-service
    deploy:
      replicas: 2
    depends_on:
      config-server:
        condition: service_healthy
      discover-server:
        condition: service_started
      mongo-db:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discover-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=ronnyseverino4@gmail.com
      - SPRING_MAIL_PASSWORD=wodpcogxwozhxlxu
    networks:
      - hotel-network

  # -------------------------
  # API GATEWAY
  # -------------------------

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
      discover-server:
        condition: service_started
      security-service:
        condition: service_started
      catalog-service:
        condition: service_started
      review-service:
        condition: service_started
      notification-service:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discover-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    networks:
      - hotel-network

  # -------------------------
  # FRONTEND DE PRUEBAS
  # -------------------------

  paypal-tester-frontend:
    build: ./paypal-tester-frontend
    container_name: paypal-tester-frontend
    ports:
      - "3000:80"
    networks:
      - hotel-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      # Ayuda a que el Hot-Reload funcione mejor en Docker Desktop
      - CHOKIDAR_USEPOLLING=true
    networks:
      - hotel-network

# -------------------------
# REDES PERSONALIZADAS
# -------------------------
networks:
  hotel-network:
    driver: bridge

volumes:
  frontend_node_modules:
