# Servidor
server.port=8000

spring.application.name=mockup-api

# Base de Datos H2 
spring.datasource.url=jdbc:h2:mem:mockdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar consola H2 (Acceso en navegador: /h2-console)
spring.h2.console.enabled=true

# Importante para Spring Security: permitir frames
spring.h2.console.settings.web-allow-others=true

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Internacionalización (i18n) 
spring.messages.basename=messages/messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true