server:
  # Puerto estipulado en este sprint para el catalogo
  port: 8081

spring:
  application:
    name: catalog-service
  data:
    mongodb:
      host: mongo-db
      port: 27017
      database: hotel_catalog_db

eureka:
  client:
    service-url:
      defaultZone: http://discover-server:8761/eureka/
  instance:
    prefer-ip-address: true
